version: '2.4'

services:
  subtitler:
    build:
      context: .
      dockerfile: Dockerfile
    image: subtitler:${release_num}
    container_name: subtitler
    restart: "no"
    volumes:
      - ../src:/app:ro
    network_mode: none
    ulimits:
      memlock: -1
      stack: 67108864

  subtitler-with-net:
    build:
      context: .
      dockerfile: Dockerfile
    image: subtitler:${release_num}
    container_name: subtitler
    restart: "no"
    volumes:
      - ../src:/app:ro
    ulimits:
      memlock: -1
      stack: 67108864
